### ISSUE TITLE
Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by mhsjlw** [zone117x/node-multi-hashing#31]
Hi! I've got node `5.3.0` installed with npm `3.3.12` installed and gcc `4.8.4`

When I run `npm update` on node-open-mining-portal when it reaches the `stratum-pool` dependency `node-gyp rebuild` fails with exit code 1. I've found that it is because of the module `multi-hashing`.

Is multi-hashing broken with my version of node? Do I need node `0.10`? I don't really want to install that as it's pretty outdated.

Thanks for any help.

**Comment by erm3nda** [comment]
This may look nonsense, but download zip or clone repo then install like `npm install ./node-multi-hashing`. I've spent many hours trying to compile that module from SEVERAL machines, so finally i've tried downloading packages. Anyway, installing stuff on npm has become a kidding experience for me. Hate it.

**Comment by mhsjlw** [comment]
I tried both `git clone` and downloading it from zip then using `npm install` to install the package locally and neither worked. Any other suggestions?

**Comment by erm3nda** [comment]
Yes, one more: download this 
https://mega.nz/#!bBtHQLrJ!c9fNeG45BlQo8dcY-i-jCykzRNbShZm1oKhz0nnqmK8
 pre-compiled module. I've built it less than hour ago, Debian 8 64bit.

Add the zip contents inside node_modules.

**Comment by mhsjlw** [comment]
I've downloaded it and placed the `multi-hashing` folder into `node_modules` but when I try to use it I get the error: `Error: Module did not self-register.`

**Comment by mhsjlw** [comment]
Also, I am using this module in [NOMP](https://github.com/zone117x/node-open-mining-portal) which requires [stratum-pool](https://github.com/zone117x/node-stratum-pool) which has a module dependency for [multi-hashing](https://github.com/zone117x/node-multi-hashing) which is why I created the issue here. I've placed the multi-hashing folder that you gave me in the `node_modules` folder of stratum-pool which is in the `node_modules` folder of NOMP because that is where I thought it was supposed to be.

**Comment by erm3nda** [comment]
I had your same problem building unomp, wich SAME dependancy and only get it compiled from a Linux Machine. Im not a regular user of Node, so I didn't know that i can't simply copy the folder. Im stucked in the same place. I'll come here if found anything new.

**Comment by erm3nda** [comment]
Also, readed something about use Node 0.10 for `multi-hashing` module.

**Comment by mhsjlw** [comment]
I'm going to look into rewriting the module so that it can be used with newer versions of node

**Comment by mhsjlw** [comment]
Can you tell me how you built the library on Debian? What version of Node.js and NPM did you have and what commands did you use to install it?

**Comment by erm3nda** [comment]
I've built in my own Laptop using Debian 8 Jessie x64, and finally did the work.
```
SOLINK_MODULE(target) Release/obj.target/multihashing.node: Finished
COPY Release/multihashing.node
make: Leaving directory '/home/m3nda/test/compile/node_modules/multi-hashing/build'
multi-hashing@0.0.9 node_modules/multi-hashing
└── bindings@1.2.1
```
Also created a VPS with Debian 8 Jessie and worked again, succesfully run the `unomp`. Dependancy `build-essentials`, `libssl-dev` and nothing more.

But, i've tried 2 more Linux boxes without luck before.

Try Debian if you can.

**Comment by erm3nda** [comment]
In another server I have with CentOS 7 i got: 
```
Error: Cannot find module './lib/cookies'
```
but module compiles too.

**Comment by erm3nda** [comment]
On Windows was impossible to build dependancy `bignum`

**Comment by mhsjlw** [comment]
Ok, I've figured out the problem: This project is build using node `0.10`, hence the binding support is also for node `0.10`. I am rewriting the bindings using [nan](https://www.npmjs.com/package/nan) so that it will support node `0.10` all the way to node `4.0.0`. I will keep you updated.

**Comment by nahy** [comment]
Find a fix for node 0.12.9. Trying update it to node 5.0 and NAN ^2.0 make me crazy tonight))
Here pull request https://github.com/zone117x/node-multi-hashing/pull/32

**Comment by mhsjlw** [comment]
I've already read the issue that you got that code from. I have also already re-written the bindings to make them work with node 4.3.0. Feel free to make them work with node 5.0 I've already tried with no success

**Comment by crusher72** [comment]
Can you share the updated bindings?

**Comment by buechling** [comment]
great. so here is the command line for non-experts: 
install this module on a modern version of node ( 6.9.4 ):

	cd node_modules
	git clone https://github.com/UNOMP/node-multi-hashing
	cd node-multi-hashing
	git checkout pull/5
	git fetch origin pull/5/head:BRANCHNAME
	git checkout BRANCHNAME
	npm install

**Comment by edilio** [comment]
What buechling did worked for me on ubuntu 16.x, node -v == v6.10.0, and npm -v == 3.10.10

**Comment by sanitariu** [comment]
On node-js version 4.6.1 does not work too.

../multihashing.cc:255:77: error: no matching function for call to 'v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))'
     exports->Set(String::NewSymbol("scryptn"), FunctionTemplate::New(scryptn)->GetFunction());

........

**Comment by nibbons** [comment]
My fix was forcing node v0.10.29 with nvp install 0.10.29 (no luck with 6.x or 0.10.48)

**Comment by adrianfako** [comment]
Try renaming the folder from multihashing to multi-hashing in node_modules.

**Comment by xeddmc** [comment]
Not sure if this still exists for you guys, but I successfully worked around this issue using nvm. Here is the curl command to install nvm if you would like it
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.3/install.sh | bash`

After that just run `nvm install 0.10.25`

Worked on every machine i've tested so far.

**Comment by mikhailrojo** [comment]
well, node@0.10.29 worked for me on linux 
but on mac 0.10.25 or 0.10.29 - no success

I guess it is linux only

**Comment by sherifomran** [comment]
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

**Comment by fmarines** [comment]
node 0.10.48 centos 7 works
